# Generated by Django 3.0.5 on 2021-12-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphanage_management', '0002_donor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('age', models.IntegerField()),
                ('special_skills', models.CharField(max_length=50)),
                ('when_we_found', models.DateTimeField()),
                ('where_we_found', models.CharField(max_length=50)),
                ('who_gave', models.CharField(max_length=15)),
                ('disability', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
