# Generated by Django 3.0.5 on 2021-12-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphanage_management', '0008_auto_20211209_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('purpose', models.TextField()),
                ('currency', models.CharField(max_length=50)),
                ('amount', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Donor',
        ),
    ]
