# Generated by Django 3.0.5 on 2021-12-12 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orphanage_management', '0011_auto_20211211_2136'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Volunteer1',
            new_name='Volunteer',
        ),
    ]
